# Generated by Django 3.2.5 on 2021-08-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_remove_order_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderStatus',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Production', 'Production'), ('Shipped', 'Shipped')], default='Pending', max_length=20, null=True),
        ),
    ]
