# Generated by Django 3.2.5 on 2021-08-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatEarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('friendly_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='QuipuForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quipu_color', models.CharField(choices=[('PW', 'Pearl White'), ('LB', 'Light Blue'), ('IP', 'Iridecent Purple'), ('TU', 'Turquoise'), ('IB', 'Iridecent Dark Blue'), ('SG', 'Scarabeus Green'), ('MA', 'Mauve'), ('BU', 'Burgundy'), ('BX', 'Bordeaux')], default='PW', max_length=2)),
                ('quipu_stone_pearl', models.CharField(choices=[('LB', 'Labradorite'), ('AM', 'Amethyst'), ('ML', 'Malachite'), ('RQ', 'Rose Quartz'), ('CI', 'Citrine'), ('GA', 'Garnet')], default='LB', max_length=2)),
                ('name_field', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('catears_has_colors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.catearcolor')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('qupiu_custom_form', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quipuform')),
            ],
        ),
    ]
