# Generated by Django 3.2.5 on 2021-08-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_qupiu_custom_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='catears_has_colors',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qupiu_custom_form',
        ),
        migrations.AddField(
            model_name='product',
            name='customer_selection',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.CreateModel(
            name='CustomerSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catears_has_colors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.catearcolor')),
                ('qupiu_custom_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quipuform')),
            ],
        ),
    ]
