# Generated by Django 3.2.5 on 2021-08-14 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210813_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEarColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='QuipuForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_field', models.CharField(max_length=12)),
                ('quipu_color', models.CharField(choices=[('PW', 'Pearl White'), ('LB', 'Light Blue'), ('IP', 'Iridecent Purple'), ('TU', 'Turquoise'), ('IB', 'Iridecent Dark Blue'), ('SG', 'Scarabeus Green'), ('MA', 'Mauve'), ('BU', 'Burgundy'), ('BX', 'Bordeaux')], default='PW', max_length=2)),
                ('quipu_stone_pearl', models.CharField(choices=[('LB', 'Labradorite'), ('AM', 'Amethyst'), ('ML', 'Malachite'), ('RQ', 'Rose Quartz'), ('CI', 'Citrine'), ('GA', 'Garnet')], default='LB', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='quipu_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quipu_stonepearl',
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='product',
            name='qupiu_custom_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quipuform'),
        ),
        migrations.AlterField(
            model_name='product',
            name='catears_has_colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.catearcolor'),
        ),
    ]
