# Generated by Django 3.2.5 on 2021-08-21 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210821_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerselection',
            name='catears_has_colors',
        ),
        migrations.RemoveField(
            model_name='customerselection',
            name='qupiu_custom_form',
        ),
        migrations.AddField(
            model_name='customerselection',
            name='option_html',
            field=models.CharField(default=None, max_length=4000),
        ),
        migrations.AddField(
            model_name='customerselection',
            name='option_name',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='customerselection',
            name='option_type',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='customerselection',
            name='sku',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
