# Generated by Django 3.2.5 on 2021-08-22 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210821_1938'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerSelection',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer_selection',
        ),
        migrations.AddField(
            model_name='product',
            name='catears_has_colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.catearcolor'),
        ),
        migrations.AddField(
            model_name='product',
            name='qupiu_custom_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quipuform'),
        ),
    ]
