# Generated by Django 3.2.5 on 2021-08-22 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210822_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='catears_has_colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.catearcolor'),
        ),
        migrations.AlterField(
            model_name='product',
            name='qupiu_custom_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.quipuform'),
        ),
    ]
